### ISSUE TITLE
版本的一些问题 

### ISSUE THREAD

**Issue by jiawenquan** [Tumiz/DrivingSchool#1]
1、这个版本应该时 python 2.7 目前 大部分都在使用3.6版本
2、torch 这个轮子 可能没有3.6 版本 我尝试升级安装不成功

希望升级到 3.6版本

**Comment by Tumiz** [comment]
1.对，目前是用2.7写的，我把个别语法问题改一下，3.6就应该能用，你可以把遇到的error贴出来
2.torch全称是pytorch，有3.6版本的，你可以在其[官网](https://pytorch.org/get-started/locally/)下载

**Comment by Tumiz** [comment]
现在只支持3.x版本了，我测试过了，可以用
